[workspace]
authors = ["Anna Monson <agm0047@uah.edu>"]
channels = ["conda-forge"]
name = "CE_9"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyter = ">=1.1.1,<2"
notebook = ">=7.5.5,<8"
